name: Add Released label (PR)

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-label-to-pr:
    if: github.event.pull_request.merged && !contains(github.event.pull_request.labels.*.name, 'Released') && !contains(github.event.pull_request.labels.*.name, 'Prerelease')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        id: released-label
        with:
            github_token: "${{ secrets.GITHUB_TOKEN }}"
            labels: 'Released'
